name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
- name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      # Enable Nx Cloud task distribution if needed
      # - run: yarn dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Record commands with Nx Cloud (optional)
      # - run: yarn nx-cloud record -- echo Hello World

      # Nx Affected runs only tasks affected by the changes in this PR/commit
      - run: yarn nx affected -t lint test build
